name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ceedling-tests:
    name: Ceedling • Ubuntu • coverage
    runs-on: ubuntu-24.04
    defaults: { run: { working-directory: basics/tests } }

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev gcc make gcovr lcov
          sudo gem install ceedling -v 1.0.0

      - name: Coverage (gcov/gcovr or lcov)
        run: |
          ceedling gcov:all
          lcov --directory build --capture --output-file coverage.info || true
          genhtml coverage.info --output-directory coverage_html || true

      - name: Upload coverage & reports
        uses: actions/upload-artifact@v4
        with:
          name: ceedling-reports
          path: |
            basics/tests/build/artifacts/gcov/**
            basics/tests/coverage.info
            basics/tests/coverage_html/**
          if-no-files-found: ignore
          retention-days: 7
